### ISSUE TITLE
Boilerplate feels incomplete (restricted area with cognito user pool authorization needed)

### ISSUE THREAD

**Issue by kidsil** [laardee/serverless-authentication-boilerplate#29]
Hey,
I've been working with this boilerplate on and off, but it feels incomplete.
Now that API Gateway allows [Authorization via Cognito User Pools](http://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html), I feel like there should be an example included of a restricted zone that is only accessible via a user pool user.

Serverless.yml supports this type of authorization, but I couldn't get it to work myself (otherwise I would've sent a Pull Request..).

**Comment by laardee** [comment]
@kidsil  I've thought about it also and that would be a great feature. How far did you manage to implement it?

**Comment by kidsil** [comment]
Sadly not very far, I've tried over and over again to get a request through the Authorizer (following the [docs](http://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html#apigateway-invoke-api-integrated-with-cognito-user-pool)) without any luck.

That's how the _events_ portion of my _main/serverless.yml_ config file looks like:
```
    events:
      - http:
          path: restricted
          method: get
          cors: true
          integration: lambda
          authorizer:
            arn: arn:aws:cognito-idp:AWS_REGION:AWS_ACCOUNT_ID:userpool/AWS_USERPOOL_ID
            resultTtlInSeconds: 0
            claims:
              - email
              - name
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*

```
