### ISSUE TITLE
Getting errors when do serverless deploy

### ISSUE THREAD

**Issue by nguyenlocduy** [laardee/serverless-authentication-boilerplate#50]
```
serverless deploy --verbose

<--- Last few GCs --->

   57874 ms: Scavenge 1323.2 (1434.4) -> 1323.2 (1434.4) MB, 24.8 / 0 ms [allocation failure].
   57899 ms: Scavenge 1323.2 (1434.4) -> 1323.2 (1434.4) MB, 24.7 / 0 ms [allocation failure].
   57924 ms: Scavenge 1323.2 (1434.4) -> 1323.2 (1434.4) MB, 25.0 / 0 ms [allocation failure].
   57949 ms: Scavenge 1323.2 (1434.4) -> 1323.2 (1434.4) MB, 24.8 / 0 ms [allocation failure].
   57973 ms: Scavenge 1323.2 (1434.4) -> 1323.2 (1434.4) MB, 24.8 / 0 ms [allocation failure].


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: Scavenger: semi-space copy
 Allocation failed - process out of memory
[1]    47248 abort      serverless deploy --verbose
```

**Comment by nileshdt** [comment]
I am getting the same errors aswell.

**Comment by cedric25** [comment]
I was facing the same issue with serverless 1.18.1 or 1.19.0.
Using a 1.9.0 unblocked me.

**Comment by ValkyrieUK** [comment]
I had to nest the `environment` object inside the `custom` section.

```yaml
  custom:
    environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
```

And then reference variables like so.
```yaml
TableName: ${self:provider.custom.environment.CACHE_DB_NAME}
```
I also changes the `env.yaml` file too something like this.

```yaml
# variables for "dev" stage
dev:
# General
  SERVICE: ${self:service}
  STAGE: ${opt:stage, self:provider.stage}
  REGION: ${opt:region, self:provider.region}
  REDIRECT_CLIENT_URI: http://127.0.0.1:3000/
  TOKEN_SECRET: token-secret-123
# Database
  CACHE_DB_NAME: ${self:service}-cache-${opt:stage, self:provider.stage}
  USERS_DB_NAME: ${self:service}-users-${opt:stage, self:provider.stage}
# Cognito
  USER_POOL_ID: eu-west-mypool-id
# Providers
  PROVIDER_FACEBOOK_ID: fb-mock-id
  PROVIDER_FACEBOOK_SECRET: fb-mock-secret
  PROVIDER_GOOGLE_ID: g-mock-id
  PROVIDER_GOOGLE_SECRET: cg-mock-secret
  PROVIDER_MICROSOFT_ID: ms-mock-id
  PROVIDER_MICROSOFT_SECRET: ms-mock-secret
  PROVIDER_CUSTOM_GOOGLE_ID: g-mock-id
  PROVIDER_CUSTOM_GOOGLE_SECRET: cg-mock-secret
```

Then when deploying pass in stage and region flags.

`sls deploy --stage dev --region eu-west-1`
